all: main.c client_handler.c client_process.c net_msgs.c pool_reader.c server_collision.c server_misc.c server_structs.c server_update.c spel_ai.c spel_objects.c
	gcc main.c client_handler.c client_process.c pool_reader.c server_collision.c server_misc.c server_structs.c net_msgs.c server_update.c spel_ai.c spel_objects.c -o main -lSDL2 -lSDL2_net -pthread -std=c99
